[[atlas]]
name = "lockscreen"

[[atlas.sprite]]
name = "backspace"
path = "assets/backspace.png"

[[atlas.font]]
name = "geist_mono"
path = "assets/GeistMono-Regular.ttf"
sizes = [128, 46, 24, 36, 12]
